import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const rendererRoot = path.join(process.cwd(), 'src', 'renderer')

function readRendererFile(relativePath: string) {
  return fs.readFileSync(path.join(rendererRoot, relativePath), 'utf8')
}

function assertPathExists(relativePath: string) {
  assert.equal(
    fs.existsSync(path.join(rendererRoot, relativePath)),
    true,
    `${relativePath} should exist`
  )
}

test('renderer shared type/model skeleton exists', () => {
  const requiredPaths = [
    'types/index.ts',
    'types/core/index.ts',
    'types/api/index.ts',
    'types/component/index.ts',
    'types/audio/index.ts',
    'model/index.ts',
    'pages/Home/types/index.ts',
    'pages/Home/model/index.ts',
    'pages/PlayList/types/index.ts',
    'pages/PlayList/model/index.ts',
    'pages/Downloads/types/index.ts',
    'pages/Downloads/model/index.ts',
    'components/SearchDialog/types/index.ts',
    'components/SearchDialog/model/index.ts',
    'components/TrackList/types/index.ts',
    'components/TrackList/model/index.ts',
    'components/LoginDialog/types/index.ts',
    'components/LoginDialog/model/index.ts',
    'components/PlayerScene/types/index.ts',
    'components/PlayerScene/model/index.ts',
    'components/Account/types/index.ts',
    'components/Account/model/index.ts',
    'components/ArtistCover/types/index.ts',
    'components/ArtistCover/model/index.ts',
    'components/AvatarCover/types/index.ts',
    'components/AvatarCover/model/index.ts',
    'components/CoverCard/types/index.ts',
    'components/CoverCard/model/index.ts',
    'components/Header/types/index.ts',
    'components/Header/model/index.ts',
    'components/MusicContextMenu/types/index.ts',
    'components/MusicContextMenu/model/index.ts',
    'components/MediaDetailHero/types/index.ts',
    'components/MediaDetailHero/model/index.ts',
    'components/PlaybackControl/types/index.ts',
    'components/PlaybackControl/model/index.ts',
    'components/PlaybackQueueDrawer/types/index.ts',
    'components/PlaybackQueueDrawer/model/index.ts',
    'components/CloseWindowDialog/types/index.ts',
    'components/CloseWindowDialog/model/index.ts',
    'components/CollectToPlaylistDrawer/types/index.ts',
    'components/CollectToPlaylistDrawer/model/index.ts',
    'components/ScrollToTopButton/types/index.ts',
    'components/ScrollToTopButton/model/index.ts',
    'components/ui/types/index.ts',
    'components/ui/model/index.ts',
    'pages/Artists/types/index.ts',
    'pages/Artists/model/index.ts',
    'pages/Artists/Detail/types/index.ts',
    'pages/Artists/Detail/model/index.ts',
    'pages/Albums/types/index.ts',
    'pages/Albums/model/index.ts',
    'pages/Albums/Detail/types/index.ts',
    'pages/Albums/Detail/model/index.ts',
    'pages/Library/types/index.ts',
    'pages/Library/model/index.ts',
    'pages/Settings/types/index.ts',
    'pages/Settings/model/index.ts',
    'pages/DailySongs/types/index.ts',
    'pages/DailySongs/model/index.ts',
    'pages/LikedSongs/types/index.ts',
    'pages/LikedSongs/model/index.ts',
    'pages/Charts/types/index.ts',
    'pages/Charts/model/index.ts',
    'pages/Mv/Detail/types/index.ts',
    'pages/Mv/Detail/model/index.ts',
    'pages/Mv/types/index.ts',
    'pages/Mv/model/index.ts',
  ]

  requiredPaths.forEach(assertPathExists)
})

test('target renderer files no longer declare business interface or type definitions inline', () => {
  const targetFiles = [
    'pages/Home/components/AlbumCard.tsx',
    'pages/Home/components/DailyFeatureCard.tsx',
    'pages/Home/components/FmFeatureCard.tsx',
    'pages/Home/components/NewAlbumList.tsx',
    'pages/Home/components/NewSongsList.tsx',
    'pages/Home/components/SongItem.tsx',
    'pages/Home/components/TopArtists.tsx',
    'pages/PlayList/index.tsx',
    'pages/PlayList/components/OnlinePlaylistFeatureCard.tsx',
    'pages/PlayList/components/AllPlayList/index.tsx',
    'pages/PlayList/components/AllPlayList/CategoriesPanel.tsx',
    'pages/PlayList/Detail/components/PlaylistDetailHero.tsx',
    'pages/PlayList/Detail/components/PlaylistDetailMoreActions.tsx',
    'pages/PlayList/Detail/components/PlaylistTrackTable.tsx',
    'pages/Downloads/components/DownloadsFilterTabs.tsx',
    'pages/Downloads/components/DownloadsPageView.tsx',
    'pages/Downloads/components/DownloadsTaskList.tsx',
    'pages/Downloads/components/DownloadTaskRow.tsx',
    'components/SearchDialog/components/SearchInputBar.tsx',
    'components/SearchDialog/components/SearchResultList.tsx',
    'components/SearchDialog/components/SearchResultRow.tsx',
    'components/TrackList/index.tsx',
    'components/TrackList/TrackListItem.tsx',
    'components/LoginDialog/components/QrLoginPanel.tsx',
    'components/PlayerScene/PlayerSceneAmllBackground.tsx',
    'components/PlayerScene/PlayerSceneAmllBackgroundOverlay.tsx',
    'components/PlayerScene/PlayerSceneAmllLyrics.tsx',
    'components/PlayerScene/PlayerSceneArtwork.tsx',
    'components/PlayerScene/PlayerSceneChromeButton.tsx',
    'components/PlayerScene/PlayerSceneControls.tsx',
    'components/PlayerScene/PlayerSceneLyrics.tsx',
    'components/PlayerScene/PlayerSceneProgress.tsx',
    'components/PlayerScene/WaterRippleCover.tsx',
    'components/Account/index.tsx',
    'components/ArtistCover/index.tsx',
    'components/AvatarCover/index.tsx',
    'components/CoverCard/index.tsx',
    'components/Header/index.tsx',
    'components/Header/WindowControls.tsx',
    'components/MusicContextMenu/index.tsx',
    'components/MediaDetailHero/index.tsx',
    'components/PlaybackControl/index.tsx',
    'components/PlaybackControl/PlaybackEngine.tsx',
    'components/PlaybackQueueDrawer/index.tsx',
    'components/CloseWindowDialog/index.tsx',
    'components/CollectToPlaylistDrawer/components/CollectToPlaylistCreateForm.tsx',
    'components/CollectToPlaylistDrawer/components/CollectToPlaylistTargetList.tsx',
    'components/CollectToPlaylistDrawer/components/CollectToPlaylistSongSummary.tsx',
    'components/ScrollToTopButton/index.tsx',
    'components/ui/carousel.tsx',
    'components/ui/color-picker.tsx',
    'pages/Artists/components/ArtistCard.tsx',
    'pages/Artists/components/ArtistFilters.tsx',
    'pages/Artists/Detail/index.tsx',
    'pages/Artists/Detail/components/ArtistDescription.tsx',
    'pages/Artists/Detail/components/ArtistHero.tsx',
    'pages/Artists/Detail/components/ArtistLatestRelease.tsx',
    'pages/Artists/Detail/components/ArtistMediaTabs.tsx',
    'pages/Artists/Detail/components/ArtistTopSongs.tsx',
    'pages/Artists/Detail/components/SimilarArtists.tsx',
    'pages/Albums/index.tsx',
    'pages/Albums/Detail/index.tsx',
    'pages/Albums/components/AlbumCard.tsx',
    'pages/Albums/components/AlbumFilters.tsx',
    'pages/Albums/Detail/components/AlbumDetailHero.tsx',
    'pages/Albums/Detail/components/AlbumTrackTable.tsx',
    'pages/Library/index.tsx',
    'pages/Library/components/CreatePlaylistDialog.tsx',
    'pages/Library/components/LibraryAlbumPanel.tsx',
    'pages/Library/components/LibraryArtistPanel.tsx',
    'pages/Library/components/LibraryCloudPanel.tsx',
    'pages/Library/components/LibraryHero.tsx',
    'pages/Library/components/LibraryMvCard.tsx',
    'pages/Library/components/LibraryMvPanel.tsx',
    'pages/Library/components/LibraryPlaylistPanel.tsx',
    'pages/Library/components/LibraryQuickSongList.tsx',
    'pages/Library/components/LibraryTabsSection.tsx',
    'pages/Settings/index.tsx',
    'pages/Settings/components/BasicSettings.tsx',
    'pages/Settings/components/PlaySettings.tsx',
    'pages/Settings/components/SystemSettings.tsx',
    'pages/Settings/components/ShortcutKeySettings.tsx',
    'pages/Settings/components/MusicSourceSettingsDialog.tsx',
    'pages/Settings/components/EqualizerSettingsDialog.tsx',
    'pages/DailySongs/components/DailySongsHero.tsx',
    'pages/LikedSongs/components/LikedSongsHero.tsx',
    'pages/LikedSongs/components/LikedSongsTrackPanel.tsx',
    'pages/Charts/components/CoreRankings/index.tsx',
    'pages/Charts/components/GenreCharts/index.tsx',
    'pages/Mv/Detail/components/MvDetailHeader.tsx',
    'pages/Mv/Detail/components/MvDetailPlayer.tsx',
    'pages/Mv/Detail/components/SimilarMvCard.tsx',
    'pages/Mv/Detail/components/SimilarMvSection.tsx',
    'pages/Home/home.model.ts',
    'pages/DailySongs/daily-songs.model.ts',
    'pages/Mv/mv-detail.model.ts',
    'pages/PlayList/Detail/playlist-detail.model.ts',
    'pages/Albums/Detail/album-detail.model.ts',
    'pages/LikedSongs/liked-songs.model.ts',
    'pages/Library/library.model.ts',
    'pages/Library/library-albums.model.ts',
    'pages/Library/library-artists.model.ts',
    'pages/Library/library-cloud.model.ts',
    'pages/Library/library-mvs.model.ts',
    'components/Account/account-menu.model.ts',
    'components/CloseWindowDialog/close-window.model.ts',
    'components/TrackList/track-list-download.model.ts',
    'components/LoginDialog/login-dialog.model.ts',
    'pages/PlayList/Detail/playlist-detail-actions.model.ts',
    'pages/PlayList/Detail/playlist-detail-refresh.model.ts',
  ]

  const declarationPattern =
    /^\s*(export\s+)?(?:interface|type)\s+[A-Za-z_]\w*(?:\s*[={<]|$)/m

  targetFiles.forEach(relativePath => {
    const content = readRendererFile(relativePath)
    assert.equal(
      declarationPattern.test(content),
      false,
      `${relativePath} should not declare business interface/type inline`
    )
  })
})
